version: '3'

services:
  radio_player:
    build: .
    working_dir: /radio/
    env_file: .env
    user: "${UID}"
    environment: 
      - "PULSE_SERVER=unix:/run/user/${UID}/pulse/native"
    volumes:
      - "/usr/share/alsa:/usr/share/alsa"
      - "/run/user/${UID}/pulse/native:/run/user/${UID}/pulse/native"
    restart: unless-stopped
