version: '3'

services:
  radio_player:
    build: .
    working_dir: /radio/
    env_file: .env
    user: "${UID}"
    environment: 
      - "PULSE_SERVER=unix:/tmp/pulseaudio.socket"
    volumes:
      - type: bind
        source: "/usr/share/alsa"
        target: "/usr/share/alsa"
      - type: bind
        source: "/run/user/${UID}/pulse/native"
        target: "/tmp/pulseaudio.socket"
    restart: unless-stopped
